apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-50f89a6b-2a8c-451f-bddf-2d7efb75110e
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app-50f89a6b-2a8c-451f-bddf-2d7efb75110e
  template:
    metadata:
      labels:
        app: springboot-app-50f89a6b-2a8c-451f-bddf-2d7efb75110e
    spec:
      containers:
      - name: springboot
        image: ravi8881/2e49f282-85d5-4866-af7d-8133a75e6769--bc5fa525-1f32-4c53-bf17-b98dd59ff12e-d9ae9c25-4bc5-4507-83f9-edf988812194-graph:0.1.0
        ports:
        - containerPort: 8081
