apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress-50f89a6b-2a8c-451f-bddf-2d7efb75110e
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: springboot-app-50f89a6b-2a8c-451f-bddf-2d7efb75110e
spec:
  ingressClassName: nginx
  rules:
    - host: tms-awj5np.ui1781.us-east-2.febe.kbs
      http:
        paths:
          - backend:
              service:
                name: springboot-service-50f89a6b-2a8c-451f-bddf-2d7efb75110e
                port:
                  number: 80
            path: /graphiql
            pathType: Prefix
          - backend:
              service:
                name: springboot-service-50f89a6b-2a8c-451f-bddf-2d7efb75110e
                port:
                  number: 80
            path: /graphql
            pathType: Prefix