apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-99c6f191-c106-4300-9ff2-15ab7314c964
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app-99c6f191-c106-4300-9ff2-15ab7314c964
  template:
    metadata:
      labels:
        app: springboot-app-99c6f191-c106-4300-9ff2-15ab7314c964
    spec:
      containers:
      - name: springboot
        image: ravi8881/2e49f282-85d5-4866-af7d-8133a75e6769--bc5fa525-1f32-4c53-bf17-b98dd59ff12e-d9ae9c25-4bc5-4507-83f9-edf988812194-graph:0.0.1
        ports:
        - containerPort: 8081
