apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress-aa7098b5-0f03-4f41-bb10-db9a919a52eb
  namespace: 3219e62e-f28c-4e9a-b62e-77aae69fb44b
  labels:
    app: springboot-app-aa7098b5-0f03-4f41-bb10-db9a919a52eb
spec:
  ingressClassName: nginx
  rules:
    - host: goal-4bfo6f.73b9nq.us-east-2.febe.kbs
      http:
        paths:
          - backend:
              service:
                name: springboot-service-aa7098b5-0f03-4f41-bb10-db9a919a52eb
                port:
                  number: 80
            path: /graphiql
            pathType: Prefix
          - backend:
              service:
                name: springboot-service-aa7098b5-0f03-4f41-bb10-db9a919a52eb
                port:
                  number: 80
            path: /graphql
            pathType: Prefix