apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress-6b2273ee-92f6-45d2-b731-fa95e1cde686
  namespace: 3219e62e-f28c-4e9a-b62e-77aae69fb44b
  labels:
    app: springboot-app-6b2273ee-92f6-45d2-b731-fa95e1cde686
spec:
  ingressClassName: nginx
  rules:
    - host: busgraph-s5mzwt.y9g47m.us-east-2.febe.kbs
      http:
        paths:
          - backend:
              service:
                name: springboot-service-6b2273ee-92f6-45d2-b731-fa95e1cde686
                port:
                  number: 80
            path: /graphiql
            pathType: Prefix
          - backend:
              service:
                name: springboot-service-6b2273ee-92f6-45d2-b731-fa95e1cde686
                port:
                  number: 80
            path: /graphql
            pathType: Prefix