apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress-b6aa7816-8002-4b22-bf6b-5b85b15f49b2
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: springboot-app-b6aa7816-8002-4b22-bf6b-5b85b15f49b2
spec:
  ingressClassName: nginx
  rules:
    - host: hrms-b8d8hn.5427b8.us-east-2.febe.kbs
      http:
        paths:
          - backend:
              service:
                name: springboot-service-b6aa7816-8002-4b22-bf6b-5b85b15f49b2
                port:
                  number: 80
            path: /graphiql
            pathType: Prefix
          - backend:
              service:
                name: springboot-service-b6aa7816-8002-4b22-bf6b-5b85b15f49b2
                port:
                  number: 80
            path: /graphql
            pathType: Prefix