apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress-05a9a253-a873-43ca-8913-d317e491c165
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: springboot-app-05a9a253-a873-43ca-8913-d317e491c165
spec:
  ingressClassName: nginx
  rules:
    - host: project-2-b80hn8.7ns0j3.us-east-2.febe.kbs
      http:
        paths:
          - backend:
              service:
                name: springboot-service-05a9a253-a873-43ca-8913-d317e491c165
                port:
                  number: 80
            path: /graphiql
            pathType: Prefix
          - backend:
              service:
                name: springboot-service-05a9a253-a873-43ca-8913-d317e491c165
                port:
                  number: 80
            path: /graphql
            pathType: Prefix