apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress-0178701a-d442-4bb4-a324-5866a5617250
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: springboot-app-0178701a-d442-4bb4-a324-5866a5617250
spec:
  ingressClassName: nginx
  rules:
    - host: tms1-mcqtso.mbne4w.us-east-2.febe.kbs
      http:
        paths:
          - backend:
              service:
                name: springboot-service-0178701a-d442-4bb4-a324-5866a5617250
                port:
                  number: 80
            path: /graphiql
            pathType: Prefix
          - backend:
              service:
                name: springboot-service-0178701a-d442-4bb4-a324-5866a5617250
                port:
                  number: 80
            path: /graphql
            pathType: Prefix