apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-f8eee0fa-8d8b-4e19-8ee8-56864de7bbd8
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app-f8eee0fa-8d8b-4e19-8ee8-56864de7bbd8
  template:
    metadata:
      labels:
        app: springboot-app-f8eee0fa-8d8b-4e19-8ee8-56864de7bbd8
    spec:
      containers:
      - name: springboot
        image: ravi8881/2e49f282-85d5-4866-af7d-8133a75e6769--bc5fa525-1f32-4c53-bf17-b98dd59ff12e-c0ab55d1-3bd3-4dbb-a1c8-a80818b7e521-graph:1.0.0
        ports:
        - containerPort: 8081
