apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress-825c87fd-3f76-4865-bdf7-f4a989a45d6c
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: springboot-app-825c87fd-3f76-4865-bdf7-f4a989a45d6c
spec:
  ingressClassName: nginx
  rules:
    - host: project-3-y8e7cd.vn3frk.us-east-2.febe.kbs
      http:
        paths:
          - backend:
              service:
                name: springboot-service-825c87fd-3f76-4865-bdf7-f4a989a45d6c
                port:
                  number: 80
            path: /graphiql
            pathType: Prefix
          - backend:
              service:
                name: springboot-service-825c87fd-3f76-4865-bdf7-f4a989a45d6c
                port:
                  number: 80
            path: /graphql
            pathType: Prefix