apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress-0ffe9fe5-5bdb-4f50-ab78-018f01a3b1d3
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: springboot-app-0ffe9fe5-5bdb-4f50-ab78-018f01a3b1d3
spec:
  ingressClassName: nginx
  rules:
    - host: project-3-jd0ql9.ye3azi.us-east-2.febe.kbs
      http:
        paths:
          - backend:
              service:
                name: springboot-service-0ffe9fe5-5bdb-4f50-ab78-018f01a3b1d3
                port:
                  number: 80
            path: /graphiql
            pathType: Prefix
          - backend:
              service:
                name: springboot-service-0ffe9fe5-5bdb-4f50-ab78-018f01a3b1d3
                port:
                  number: 80
            path: /graphql
            pathType: Prefix