apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress-3cede942-2cd8-44a7-84fc-128169f9df7d
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: springboot-app-3cede942-2cd8-44a7-84fc-128169f9df7d
spec:
  ingressClassName: nginx
  rules:
    - host: project-3-drydz6.f8jq4l.us-east-2.febe.kbs
      http:
        paths:
          - backend:
              service:
                name: springboot-service-3cede942-2cd8-44a7-84fc-128169f9df7d
                port:
                  number: 80
            path: /graphiql
            pathType: Prefix
          - backend:
              service:
                name: springboot-service-3cede942-2cd8-44a7-84fc-128169f9df7d
                port:
                  number: 80
            path: /graphql
            pathType: Prefix